name: Build do Projeto

on:
  push:
    branches:
      - main   # Roda quando você fizer push na main
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou a versão que seu projeto usa

      - name: Instalar dependências
        run: npm install
        working-directory: frontend

      - name: Gerar o build
        run: npm run build
        working-directory: frontend
